### ISSUE TITLE
The server is down when there is no network

### ISSUE THREAD

**Issue by kanevk** [kanevk/gkeep-files-sync#1]
The server falls with `ReadTimeoutError` when there is no network.

Traceback:
```python
Traceback (most recent call last):
  File "sync_server.py", line 40, in <module>
    sync_note.sync_with_remote(keep)
  File "/Users/kkanev/projects/gkeep-sync/sync_note.py", line 21, in function_timer
    value = func(*args, **kwargs)
  File "/Users/kkanev/projects/gkeep-sync/sync_note.py", line 89, in sync_with_remote
    keep.sync()
  File "/Users/kkanev/.local/share/virtualenvs/gkeep-sync-BXeQRjV-/lib/python3.7/site-packages/gkeepapi/__init__.py", line 850, in sync
    changes = self._reminders_api.list()
  File "/Users/kkanev/.local/share/virtualenvs/gkeep-sync-BXeQRjV-/lib/python3.7/site-packages/gkeepapi/__init__.py", line 458, in list
    json=params
  File "/Users/kkanev/.local/share/virtualenvs/gkeep-sync-BXeQRjV-/lib/python3.7/site-packages/gkeepapi/__init__.py", line 220, in send
    response = self._send(**req_kwargs).json()
  File "/Users/kkanev/.local/share/virtualenvs/gkeep-sync-BXeQRjV-/lib/python3.7/site-packages/gkeepapi/__init__.py", line 263, in _send
    return self._session.request(**req_kwargs)
  File "/Users/kkanev/.local/share/virtualenvs/gkeep-sync-BXeQRjV-/lib/python3.7/site-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/Users/kkanev/.local/share/virtualenvs/gkeep-sync-BXeQRjV-/lib/python3.7/site-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/Users/kkanev/.local/share/virtualenvs/gkeep-sync-BXeQRjV-/lib/python3.7/site-packages/requests/adapters.py", line 529, in send
    raise ReadTimeout(e, request=request)
requests.exceptions.ReadTimeout: HTTPSConnectionPool(host='www.googleapis.com', port=443): Read timed out. (read timeout=None)
```

## Expected behavior

Sync only when there is a network.

**Comment by kanevk** [comment]
This was fixed in: 1f090006a32dd3cd94bc68302b05db0556b78a9a
